### PR TITLE
Identification schema

### PR DESCRIPTION
**Pull request by pudo**
This implements #426 with a perspective to eventually discard the `Passport` schema in a couple of versions.

### CODE REVIEW

**Review by Rosencrantz — APPROVED** [review]

**Comment by Rosencrantz** [comment]
@pudo Can you take a look at these conflicts and resolve?

**Review by Rosencrantz — APPROVED** [review]

**Review by Rosencrantz — APPROVED** [review]

**Comment by sunu** [comment]
@pudo If I understand correctly, this doesn't affect existing data and only the reverse property name changes at run time from `passport` to `identification`. Is that right?

**Comment by pudo** [comment]
Yes, this change (unlike the one I'd like to propose for license) should be fully backward compatible. Of course it will generate another index in Aleph :/

**Comment by sunu** [comment]
Got it, thanks!

**Pull request merged**
