### PR TITLE
Another one bites the dust

### PR DESCRIPTION
**Pull request by dchaplinsky**
@pudo , I think you've forgot to close one handler.

### CODE REVIEW

**Comment by dchaplinsky** [comment]
First commit didn't completely fixed it because entities are written into `_links.csv` but not to `_nodes.csv`. I've made a fix for that but I need to discuss if it's correct thing to do. Maybe we don't need to write links that goes to rdf.type = entity?

**Comment by pudo** [comment]
I'm pretty sure the exemption for entity nodes is correct since they *must* be in one of the schema-specific CSV files, unless the provided data is invalid. Do you get errors out of this?

**Comment by dchaplinsky** [comment]
Yes, I do, because they are also mentioned in _links.csv with entity:
prefix and Neo4j cannot find them. I'll look deeply into it today.

**Comment by pudo** [comment]
Discard in favour of #105

**Pull request closed without merging**
